# Generated by Django 4.1.6 on 2023-02-12 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hometasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=150)),
                ('taskenddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('taskstartdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('taskcreatedate', models.DateTimeField(default=django.utils.timezone.now)),
                ('taskdescription', models.CharField(max_length=150)),
                ('taskstatus', models.IntegerField(default=1)),
            ],
        ),
    ]
