# Generated by Django 4.1.6 on 2023-02-12 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todomainapp', '0002_alter_hometasks_taskcreatedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometasks',
            name='taskcreatedate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='hometasks',
            name='taskdescription',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hometasks',
            name='taskenddate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='hometasks',
            name='taskname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hometasks',
            name='taskstartdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='hometasks',
            name='taskstatus',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
