# Generated by Django 4.1.6 on 2023-02-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todomainapp', '0004_remove_hometasks_taskdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometasks',
            name='taskenddate',
            field=models.DateTimeField(null=True),
        ),
    ]
