# Generated by Django 4.1.6 on 2023-02-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todomainapp', '0005_alter_hometasks_taskenddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometasks',
            name='taskdescription',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
